apiVersion: v1
kind: Namespace
metadata:
  name: sre-target-apps
  labels:
    arena.sre.io/role: victim
---
apiVersion: v1
kind: Namespace
metadata:
  name: sre-arena-control
  labels:
    arena.sre.io/role: control-plane
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-defender-sa
  namespace: sre-arena-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-defender-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "events", "configmaps"]
    verbs: ["get", "list", "watch", "describe", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "deployments/rollback", "replicasets"]
    verbs: ["get", "list", "watch", "describe", "patch", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-defender-binding
subjects:
  - kind: ServiceAccount
    name: sre-defender-sa
    namespace: sre-arena-control
roleRef:
  kind: ClusterRole
  name: sre-defender-cluster-role
  apiGroup: rbac.authorization.k8s.io
